# This is a basic workflow to deploy the project to the website

name: Deploy to Github Pages

# Triggers the workflow on push or pull request but only for the master branch
on:
  push:
    branches: [ master ]
    tags:
      - v*

jobs:
  # Build the project
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:          
      - name: tsc
      uses: icrawl/action-tsc@v1
         
      # Deploy
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          # Deployed to the organisation website
          REPOSITORY_NAME: livrelogique/livrelogique.github.io/pravda
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: main
          # This is the folder the website is generated
          FOLDER: dist
          CLEAN: true
